export const USER_NAME = 'USER_NAME';
export const USER_PASSWORD = 'USER_PASSWORD';
export const VALIDATION_CHECK_LOGIN = 'VALIDATION_CHECK_LOGIN';
export const CLEAR_LOGIN_VALIDATION_ERROR = 'CLEAR_LOGIN_VALIDATION_ERROR';
export const CLEAR_LOGIN_DATA = 'CLEAR_LOGIN_DATA';
export const CLEAR_LOGIN_VALIDATION = 'CLEAR_LOGIN_VALIDATION';
